### ISSUE TITLE
TypeError: value is out of bounds

### ISSUE THREAD

**Issue by tomvandenberge** [simplereach/helenus#104]
When I try to retrieve data using the thrift driver, I'm getting the error "TypeError: value is out of bounds" when the column family is retrieved. When I do it with CQL, it works fine.

Basically, all I do is

```
pool.connect(function(err, keyspace) {
  if(err){
    throw(err);
  }
  keyspace.get('thecolumnfamily', function(err, cf){
  ...
  });
});
```

(Of course the pool is set up)
This results in the following wonderful stacktrace:

```
/Users/tom/Downloads/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:90
    throw e;
          ^
TypeError: value is out of bounds
at TypeError (<anonymous>)
at checkInt (buffer.js:781:11)
at Buffer.writeUInt32BE (buffer.js:845:5)
at Object.Serializers.encodeInteger (/Users/tom/Downloads/node_modules/helenus/lib/marshal/serializers.js:24:18)
at Serializers.encodeInt32 [as serialize] (/Users/tom/Downloads/node_modules/helenus/lib/marshal/serializers.js:66:22)
at ColumnFamily.setColumnValidator (/Users/tom/Downloads/node_modules/helenus/lib/column_family.js:207:39)
at new ColumnFamily (/Users/tom/Downloads/node_modules/helenus/lib/column_family.js:196:12)
at onComplete (/Users/tom/Downloads/node_modules/helenus/lib/keyspace.js:87:33)
at onReturn (/Users/tom/Downloads/node_modules/helenus/lib/connection.js:379:7)
at client._reqs.(anonymous function) (/Users/tom/Downloads/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:80:11)
```

Any ideas?

Thanks,
Tom

**Comment by devdazed** [comment]
What does the connection look like? are you specifying a keyspace? also, what version of C\* are you running?

**Comment by tomvandenberge** [comment]
The connection is set up like this:

```
var helenus = require('helenus'),
pool = new helenus.ConnectionPool({
    hosts      : ['localhost:9160'],
    keyspace   : 'mykeyspace',
    timeout    : 3000
});

pool.on('error', function(err){
    console.error(err.name, err.message);
});
```

I'm using this setup for the CQL variant, too, wich works fine.

I'm using cassandra 1.1.5.

**Comment by tomvandenberge** [comment]
I just upgraded my Cassandra to the latest (1.2.4), but unfortunately no difference.

**Comment by tomvandenberge** [comment]
Any luck fixing or reproducing this problem? Let me know if I can help by providing info or testing anything.

Tom
