### ISSUE TITLE
Selecting nonexistant column by name in CQL causes deserializing error

### ISSUE THREAD

**Issue by cs2dsb** [simplereach/helenus#33]
Hi,

Given a CF with the following definition:

```
CfDef ({
    keyspace                  : keyspaceName,
    name                      : 'friends',
    column_type               : 'Standard',
    comparator_type           : 'UUIDType',
    default_validation_class  : 'UTF8Type',
    key_validation_class      : 'UUIDType',
    column_metadata           : [ ]
  })
```

These are the statements I'm using and the results they give in CQLSH:

1.

```
SELECT * FROM friends WHERE key = 'd6080750-83c2-11e1-b890-5765c53d0889';
                                   KEY |
  d6080750-83c2-11e1-b890-5765c53d0889 |
```

2.

```
SELECT KEY, '7933d83b-1fce-4390-8903-6dde41ef04d3' FROM friends WHERE key = 'd6080750-83c2-11e1-b890-5765c53d0889';
                                   KEY | 7933d83b-1fce-4390-8903-6dde41ef04d3 |
  d6080750-83c2-11e1-b890-5765c53d0889 |                                 None |
```

Using helenus, (1.) works and gives a row with no columns as you'd expect but (2.) results in the following error:

```
/home/ubuntu/node.js/gog/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:90
        throw e;
^

TypeError: Cannot read property 'length' of null
    at new Buffer (buffer.js:234:37)
    at /home/ubuntu/node.js/gog/node_modules/helenus/lib/marshal/deserializers.js:59:10
    at new <anonymous> (/home/ubuntu/node.js/gog/node_modules/helenus/lib/row.js:34:33)
    at onReturn (/home/ubuntu/node.js/gog/node_modules/helenus/lib/connection.js:351:19)
    at onReturn (/home/ubuntu/node.js/gog/node_modules/helenus/lib/connection.js:283:7)
    at /home/ubuntu/node.js/gog/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:80:11
    at Object.recv_execute_cql_query (/home/ubuntu/node.js/gog/node_modules/helenus/lib/cassandra/1.0/Cassandra.js:6592:12)
    at /home/ubuntu/node.js/gog/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:83:36
    at Socket.<anonymous> (/home/ubuntu/node.js/gog/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/transport.js:70:9)
    at Socket.emit (events.js:67:17)
```

I added the following before line 34 in row.js to try and track the issue down:

```
 if (!item.value) console.log('Attempting to deserialise null/undefined' );
```

And it gets printed directly before the error is thrown.

I've deleted my copy of helenus and fetched it again from npm to rule out any changes I made (when I was finding my way around earlier!) and the error still happens.

I've also tried changing the column name to various other UUIDs, both to ones that have never existed and ones that have been deleted but not compacted-away.

I'm going to "fix" the issue locally before the deserializer is called in row.js but thought I would raise an issue given that the root cause is likely to be elsewhere; perhaps somewhere in cassandra.js or cassandra_types.js which are far to big for me to go poking around in with limited understanding.

Thanks,

Daniel

**Comment by devdazed** [comment]
I am having trouble reproducing this.  Currently i am getting a row with 0 columns for both queries.  Is this in an empty CF?  What version of C\* are you running?

Here is my test:

```
[default@test] create column family issue_33 with comparator = 'UUIDType' and default_validation_class = 'UTF8Type' and key_validation_class = 'UUIDType'; 
```

``` javascript
  var helenus = require('helenus'),
      pool = new helenus.ConnectionPool({
        hosts      : ['localhost:9160'],
        keyspace   : 'test',
        timeout    : 3000
      });

  pool.on('error', function(err){
    console.error(err.name, err.message);
  });

  pool.connect(function(err, keyspace){
    if(err){
      throw(err);
    } else {
      pool.cql("SELECT KEY, '7933d83b-1fce-4390-8903-6dde41ef04d3' FROM issue_33 WHERE key = 'd6080750-83c2-11e1-b890-5765c53d0889';", function(err, results){
        console.log(err, results);
      }); 
    }
  });
```

**Comment by cs2dsb** [comment]
Wow, quick response!

I used your create statement + code and it worked correctly. I then executed the following in cassandra-cli and was able to reproduce it:

```
[default@test] list issue_33;
Using default limit of 100

0 Row Returned.
Elapsed time: 32 msec(s).
[default@test] set issue_33['d6080750-83c2-11e1-b890-5765c53d0889']['7933d83b-1fce-4390-8903-6dde41ef04d3'] = 'fred';
Value inserted.
Elapsed time: 28 msec(s).
[default@test] list issue_33;
Using default limit of 100
-------------------
RowKey: d6080750-83c2-11e1-b890-5765c53d0889
=> (column=7933d83b-1fce-4390-8903-6dde41ef04d3, value=fred, timestamp=1334171784570000)

1 Row Returned.
Elapsed time: 22 msec(s).
[default@test] del issue_33['d6080750-83c2-11e1-b890-5765c53d0889']['7933d83b-1fce-4390-8903-6dde41ef04d3'];
column removed.
```

So it seems the row has to exist but not with the expected column. After this I set another random column so the row wasn't completely empty and the same error occurs.

Here is the stack trace it gave from a fresh folder + npm install:

```
/home/ubuntu/node.js/issue_33/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:90
        throw e;
              ^
TypeError: Cannot read property 'length' of null
    at new Buffer (buffer.js:234:37)
    at /home/ubuntu/node.js/issue_33/node_modules/helenus/lib/marshal/deserializers.js:59:10
    at new <anonymous> (/home/ubuntu/node.js/issue_33/node_modules/helenus/lib/row.js:34:33)
    at onReturn (/home/ubuntu/node.js/issue_33/node_modules/helenus/lib/connection.js:353:19)
    at onReturn (/home/ubuntu/node.js/issue_33/node_modules/helenus/lib/connection.js:284:7)
    at /home/ubuntu/node.js/issue_33/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:80:11
    at Object.recv_execute_cql_query (/home/ubuntu/node.js/issue_33/node_modules/helenus/lib/cassandra/1.0/Cassandra.js:6592:12)
    at /home/ubuntu/node.js/issue_33/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:83:36
    at Socket.<anonymous> (/home/ubuntu/node.js/issue_33/node_modules/helenus/node_modules/helenus-thrift/lib/thrift/transport.js:70:9)
    at Socket.emit (events.js:67:17)
```

Cassandra version:

```
nodetool -h localhost version
ReleaseVersion: 1.0.8
```

**Comment by devdazed** [comment]
it seems that this is an issue with tombstones.  if you try to get a column that has been deleted and the tombstone has not yet been removed, it will result in this error.  There is no real way for the driver to know if it is a tombstone, however it shouldn't crash.  I'll set the marshallers to value check and if no value comes back then it will set it to null.

**Comment by devdazed** [comment]
This will be pushed with version 0.4.0 in a day or so

**Comment by devdazed** [comment]
The latest version (0.4.0) has been published.
