### ISSUE TITLE
CQL 3.0 Tests Failing on 1.1.1

### ISSUE THREAD

**Issue by devdazed** [simplereach/helenus#57]
Tests are failing on 1.1.1, it seems to be an issue with thrift, not sure if we need to recompile or not:

```
Exception
161TypeError: Cannot read property 'length' of undefined
162    at Object.read (/home/vagrant/builds/simplereach/helenus/lib/cassandra/cassandra_types.js:3258:29)
163    at Object.read (/home/vagrant/builds/simplereach/helenus/lib/cassandra/cassandra_types.js:3444:21)
164    at Object.read (/home/vagrant/builds/simplereach/helenus/lib/cassandra/Cassandra.js:5163:22)
165    at Object.recv_execute_cql_query (/home/vagrant/builds/simplereach/helenus/lib/cassandra/Cassandra.js:6977:10)
166    at /home/vagrant/builds/simplereach/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:83:36
167    at Socket.<anonymous> (/home/vagrant/builds/simplereach/helenus/node_modules/helenus-thrift/lib/thrift/transport.js:70:9)
168    at Socket.emit (events.js:67:17)
169    at TCP.onread (net.js:367:14)
```

**Comment by devdazed** [comment]
ok , it seems somehow i checked in a newly compiled version of the thrift files with 0.8.0. not sure why or how those got generated.
