### ISSUE TITLE
1.2 Compatibility

### ISSUE THREAD

**Issue by devdazed** [simplereach/helenus#85]
There are CQL 2/3 Errors in the 1.2.0~beta1 version of C*.  

CQL2 times out during query execution.

CQL 3 has the following error when creating a keyspace using the "old style":

```
HelenusInvalidRequestException: line 1:89 mismatched input ':' expecting '='
  at onReturn (/home/travis/builds/simplereach/helenus/lib/connection.js:355:23)
  at /home/travis/builds/simplereach/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:80:11
  at Object.recv_execute_cql_query (/home/travis/builds/simplereach/helenus/lib/cassandra/Cassandra.js:6956:12)
  at /home/travis/builds/simplereach/helenus/node_modules/helenus-thrift/lib/thrift/connection.js:83:36
  at Socket.<anonymous> (/home/travis/builds/simplereach/helenus/node_modules/helenus-thrift/lib/thrift/transport.js:70:9)
  at Socket.emit (events.js:67:17)
  at TCP.onread (net.js:372:14)

```

**Comment by chris-rock** [comment]
should be solved with the latest version...
